"""
Question bank seed data for RecruitAI.
Call seed_questions() inside an app context to populate the database.
"""
from extensions import db
from models import ExamQuestion

QUESTION_BANK = {
    "Python Developer": [
        ("What is a Python decorator?","A function that modifies another function's behavior","A design pattern for objects","A type of Python variable","A method to import modules","a","Core Python"),
        ("What does GIL stand for in Python?","General Interface Layer","Global Interpreter Lock","Generic Import Library","Global Instance List","b","Core Python"),
        ("Which library is used for data manipulation?","NumPy","Matplotlib","Pandas","SciPy","c","Libraries"),
        ("What does 'yield' do in Python?","Returns a value and exits","Pauses a function and returns a value (generator)","Imports an external library","Declares a global variable","b","Advanced Python"),
        ("What is __init__ in Python classes?","Destroys objects","Class constructor called on instantiation","A static method","A module initializer","b","OOP"),
        ("How do you handle exceptions in Python?","if/else blocks","try/except blocks","switch/case","catch/throw","b","Error Handling"),
        ("What is the difference between list and tuple?","Lists store more elements","Tuples are mutable, lists immutable","Lists are mutable, tuples immutable","No difference","c","Data Structures"),
        ("What is a virtual environment?","A remote server","Isolated Python env with its own packages","A GUI framework","A debugging tool","b","Development"),
        ("What does the 'with' statement do?","Creates a loop","Defines a function","Manages context and ensures resource cleanup","Imports modules","c","Core Python"),
        ("What is the purpose of *args?","Pass keyword arguments","Pass variable number of positional arguments","Define default values","Import arguments","b","Core Python"),
        ("What is duck typing?","Duck-shaped data structures","Type system based on object behavior not class","Automatic type conversion","Testing methodology","b","Advanced Python"),
        ("What does json.loads() do?","Saves data to JSON file","Converts JSON string to Python object","Loads a JSON module","Validates JSON syntax","b","Data Formats"),
        ("What is method resolution order (MRO)?","Order methods are defined","Order Python searches for methods in inheritance","Alphabetical method sort","Async method execution order","b","OOP"),
        ("What is list comprehension?","A way to sort lists","Concise way to create lists in one line","Merge multiple lists","Delete list elements","b","Core Python"),
        ("What does @property do in Python?","Makes a method static","Allows a method to be accessed like an attribute","Creates a private variable","Imports a property from module","b","OOP"),
    ],
    "Frontend Developer": [
        ("What is the Virtual DOM in React?","A real browser DOM","Lightweight in-memory copy of DOM for efficient updates","A virtual reality interface","A database for React state","b","React"),
        ("What is the purpose of async/await?","Make code run faster","Handle async operations in synchronous-like syntax","Create multiple threads","Delay function execution","b","JavaScript"),
        ("What does HTTP status 404 mean?","Server error","Unauthorized","Resource not found","Request timeout","c","Web Fundamentals"),
        ("What is event bubbling in JavaScript?","Floating animations","Event propagation from child to parent elements","Method for creating listeners","Canceling events","b","JavaScript"),
        ("What is the purpose of webpack?","CSS preprocessor","JavaScript testing framework","Module bundler that packages assets","Backend web framework","c","Tools"),
        ("What is CORS?","CSS layout system","Security mechanism for cross-origin HTTP requests","JavaScript testing library","React state management","b","Web Security"),
        ("Difference between == and === in JavaScript?","No difference","== checks value only, === checks value and type","=== checks value only","Both check type and value","b","JavaScript"),
        ("What is a Promise in JavaScript?","Guaranteed synchronous operation","Object for eventual completion of async operation","Way to create classes","A type of variable","b","JavaScript"),
        ("What is Flexbox used for?","Animation creation","Database connections","One-dimensional layout alignment","Creating 3D effects","c","CSS"),
        ("What is semantic HTML?","HTML with inline CSS","HTML tags that describe meaning of content","Minified HTML","HTML generated by JavaScript","b","HTML"),
        ("What is localStorage?","Server-side storage","Client-side key-value storage persisting across sessions","In-memory cache clearing on reload","Database for frontend","b","Web APIs"),
        ("What is the CSS Box Model?","3D rendering system","Layout model with margin, border, padding, content","Grid system for CSS","Flexbox config method","b","CSS"),
        ("What is a REST API?","Rapid execution system tool","Stateless web service using HTTP methods","Testing framework","Real-time protocol","b","APIs"),
        ("What is z-index in CSS?","Sets transparency","Controls stacking order of overlapping elements","Zooms in on elements","Sets position from top","b","CSS"),
        ("What does 'use strict' do in JavaScript?","Makes code faster","Enables strict mode catching common errors","Imports strict library","Disables debugging","b","JavaScript"),
    ],
    "Backend Developer": [
        ("What is database indexing?","Numbering rows sequentially","Data structure speeding up data retrieval","Method to backup databases","Encrypting columns","b","Databases"),
        ("What is a foreign key?","Key to encrypt foreign data","Field referencing primary key in another table","Key from external API","Unique key for each row","b","Databases"),
        ("SQL vs NoSQL databases?","No difference","SQL uses structured schemas; NoSQL is flexible schema-less","NoSQL is always faster","SQL only for small datasets","b","Databases"),
        ("What is JWT?","JavaScript Web Toolkit","JSON Web Token for secure information transmission","Java Web Technology","JSON Write Tool","b","Security"),
        ("What is caching?","Permanently storing data","Temporarily storing data for faster future access","Deleting old records","Compressing database","b","Performance"),
        ("What is a microservices architecture?","One large application","Small independent services communicating via APIs","A database architecture","A frontend pattern","b","Architecture"),
        ("What is Docker?","A programming language","Platform to build, run, ship applications in containers","A database system","A testing framework","b","DevOps"),
        ("What is an ORM?","A REST framework","Object-Relational Mapper bridging code and database","A caching system","A message queue","b","Databases"),
        ("What is rate limiting?","Limiting data storage","Controlling request frequency to protect APIs from abuse","Limiting user accounts","A database constraint","b","API Design"),
        ("What is a message queue?","A database type","Asynchronous communication system between services","A logging system","A load balancer","b","Architecture"),
        ("What is ACID in databases?","A database query language","Atomicity, Consistency, Isolation, Durability – transaction properties","A NoSQL database","A backup strategy","b","Databases"),
        ("What is a RESTful API?","API using only GET","Architectural style using HTTP methods and stateless communication","A real-time socket API","API using only JSON","b","API Design"),
        ("What is load balancing?","Balancing database load","Distributing traffic across multiple servers","A caching technique","A security protocol","b","Architecture"),
        ("What is SQL injection?","A database optimization","Attack inserting malicious SQL code through user input","A query optimization","A join technique","b","Security"),
        ("What is a webhook?","A database trigger","HTTP callback sent when an event occurs in a system","A testing endpoint","A logging mechanism","b","API Design"),
    ],
    "Data Scientist": [
        ("What is overfitting?","Model performs well on train but poorly on unseen data","Model is too simple","Training takes too long","Dataset is too large","a","ML Concepts"),
        ("What is a confusion matrix?","A matrix that confuses the model","Table summarizing classification performance","Type of neural network layer","Data preprocessing technique","b","Model Evaluation"),
        ("What does SQL GROUP BY do?","Sorts alphabetically","Aggregates rows with same values in specified columns","Joins tables","Filters rows","b","SQL"),
        ("What is gradient descent?","Data visualization technique","Optimization algorithm minimizing a loss function","Type of decision tree","Method to normalize gradients","b","ML Algorithms"),
        ("What is a p-value?","Probability H0 is true","Probability of results as extreme assuming H0 is true","Mean of a distribution","Standard deviation of sample","b","Statistics"),
        ("Supervised vs unsupervised learning?","No difference","Supervised uses labeled data; unsupervised finds patterns in unlabeled","Supervised is faster","Unsupervised needs more data","b","ML Concepts"),
        ("What is a Random Forest?","Single decision tree","Ensemble of decision trees on random subsets","Neural network with random weights","Clustering algorithm","b","ML Algorithms"),
        ("What is feature engineering?","Building new models","Creating/transforming features to improve model performance","Removing irrelevant features","Visualizing features","b","Data Preparation"),
        ("What is cross-validation?","Combine multiple datasets","Assess model generalization on different data splits","Cross-check feature importance","Data augmentation technique","b","Model Evaluation"),
        ("What is regularization?","Makes models more complex","Penalty term to prevent overfitting","Data normalization method","Regularize training epochs","b","ML Concepts"),
        ("What is a hyperparameter?","Learned from training data","Config variable set before training, not learned from data","High-value feature","Parameter in test dataset","b","ML Concepts"),
        ("What is the Central Limit Theorem?","Mean equals median","Sample means approximate normal distribution as n increases","Large datasets are always normal","Central values are most important","b","Statistics"),
        ("What is dimensionality reduction?","Increasing features","Reducing features while preserving important information","Removing rows","Normalizing values","b","ML Concepts"),
        ("What does Pandas groupby() return?","List of DataFrames","GroupBy object for applying aggregate functions","Sorted DataFrame","Filtered dataset","b","Pandas"),
        ("What is PCA used for?","Predicting values","Reducing dimensions by finding principal components","Classifying data","Cleaning missing values","b","ML Algorithms"),
    ],
}


def seed_questions():
    print("🌱 Checking question bank...")
    count = 0
    for role, questions in QUESTION_BANK.items():
        existing = ExamQuestion.query.filter_by(job_role=role).first()
        if existing:
            continue
        print(f"   Adding questions for: {role}")
        for q in questions:
            eq = ExamQuestion(
                job_role=role, question_text=q[0],
                option_a=q[1], option_b=q[2],
                option_c=q[3], option_d=q[4],
                correct_answer=q[5],
                category=q[6] if len(q) > 6 else 'General',
            )
            db.session.add(eq)
            count += 1
    if count > 0:
        db.session.commit()
        print(f"✅ Seeded {count} new questions across {len(QUESTION_BANK)} roles")
    else:
        print(f"✅ Question bank already complete ({len(QUESTION_BANK)} roles)")
